"""
Konkle and Alvarez (2022) speculate that perceptual judgements of visual similarity might be
driven by a process of contrastive learning not unlike that in AI. Different views of the same
scene, like the augmentations used in contrastive learning, can be generated by eye movements,
body movements and the passage of time. The hippocampus could hold these views in working memory
to implement a form of contrastive learning in neocortex. These ideas are closely related to
long-standing ideas about predictive coding in the brain. This remains an active and fascinating
area of research.
"""