name: 'Setup nmaci CI Tools'
description: 'Download and install Neuromatch CI tools'

inputs:
  branch:
    description: 'nmaci branch to use'
    required: false
    default: 'main'
  commit-message:
    description: 'Commit message to parse for branch override'
    required: false
    default: ''

outputs:
  nmaci-branch:
    description: 'nmaci branch used'
    value: ${{ steps.detect-branch.outputs.branch }}

runs:
  using: 'composite'
  steps:
    - name: Detect nmaci branch
      id: detect-branch
      shell: bash
      env:
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
      run: |
        BRANCH="${{ inputs.branch }}"
        if [ -n "$COMMIT_MESSAGE" ]; then
          OVERRIDE=$(python3 -c "import os, re; m = re.search(r'nmaci:([\w-]+)', os.environ.get('COMMIT_MESSAGE', '')); print(m.group(1) if m else '')")
          if [ -n "$OVERRIDE" ]; then
            BRANCH="$OVERRIDE"
          fi
        fi
        echo "branch=$BRANCH" >> $GITHUB_OUTPUT
        echo "Using nmaci branch: $BRANCH"

    - name: Cache nmaci tools
      id: cache-nmaci
      uses: actions/cache@v3
      with:
        path: ci/
        key: nmaci-${{ runner.os }}-${{ steps.detect-branch.outputs.branch }}-v2
        restore-keys: nmaci-${{ runner.os }}-${{ steps.detect-branch.outputs.branch }}-

    - name: Download nmaci tools
      if: steps.cache-nmaci.outputs.cache-hit != 'true'
      shell: bash
      run: |
        BRANCH=${{ steps.detect-branch.outputs.branch }}
        wget -q https://github.com/neuromatch/nmaci/archive/refs/heads/$BRANCH.tar.gz
        tar -xzf $BRANCH.tar.gz
        mv nmaci-$BRANCH/scripts/ ci/
        # Preserve requirements for caching
        mv nmaci-$BRANCH/requirements.txt ci/requirements.txt
        rm -r nmaci-$BRANCH $BRANCH.tar.gz

    - name: Install nmaci dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        # Fallback: download requirements.txt if not in cache
        if [ ! -f ci/requirements.txt ]; then
          BRANCH=${{ steps.detect-branch.outputs.branch }}
          wget -q -O ci/requirements.txt https://raw.githubusercontent.com/neuromatch/nmaci/$BRANCH/requirements.txt
        fi
        pip install -r ci/requirements.txt

    - name: Ignore ci directory
      shell: bash
      run: echo "ci/" >> .gitignore
