
"""
Discussion: Why do you think we obtain zero error right away (on the first epoch)?

The deal is, the data is generated by the given network, thus there is no need to change weights at all, the gradients are zeros:)
""";